language: lua

services:
  - docker
dist: trusty

env:
  COMPOSE_VERSION: 18.06

install: docker-compose build test

before_script: luarocks install luacov-coveralls

script:
  - docker-compose run --rm test

after_success: docker-compose run --rm coverage

after_script: luacov-coveralls -v
