version: '2.1'

services:
  nginx:
    build:
      context: .
    volumes:
      - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./src/:/lua/src/"
    depends_on:
      - redis_cluster
    links:
      - redis_cluster
    ports:
      - "8080:8080"

  test:
    command: busted -v
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

  redis_cluster:
    image: grokzen/redis-cluster:latest
    ports:
      - '7000-7005:7000-7005'
