version: '2.1'

services:
  nginx:
    build:
      context: .
    volumes:
      - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./src/:/lua/src/"
    depends_on:
      - redis_cluster
    links:
      - redis_cluster
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    ports:
      - "8080:8080"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

  redis_cluster:
    image: grokzen/redis-cluster:latest
    ports:
      - '7000-7005:7000-7005'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
